### ISSUE TITLE
Fails if Qscore>=50

### ISSUE THREAD

**Issue by Phelimb** [kvarq/kvarq#2]
I'm not sure what the fastq specs are for illumina 1.8 but I think they can have quality scores > 41. 

A quote from wikipedia "For processed reads, scores may be even higher. For example, quality values of 45 are observed in reads from Illumina's Long Read Sequencing Service (previously Moleculo)." http://en.wikipedia.org/wiki/FASTQ_format

Files have failed as they have quality scores of 50. Although this is outside the expected range they don't violate the file format specs which I think is 0 - 62 http://wiki.christophchamp.com/index.php/FASTQ_format so I'm not sure if failing is the ideal behaviour.

**Comment by kvarq** [comment]
KvarQ uses heuristics to guess the right variant. We didn't encounter any illumina reads with Q>41, but I will adapt as the range for Illumina 1.8+ to 0..62 as suggested by you. I will also add a new command line switch to specify the variant if the heuristics fail.

**Comment by Phelimb** [comment]
OK, great ! 

Q scores of 50 are a little weird though so I wouldn't blame you for banning them ;)

**Comment by kvarq** [comment]
as of commit b302099 (v0.12.2) new parameter "kvarq scan --variant" introduced, also increased Illumina 1.8+ PHRED range to up to 62...
